# Generated by Django 2.2.15 on 2020-08-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ブランド')),
                ('item_model', models.CharField(max_length=50, verbose_name='モデル名')),
                ('category', models.CharField(max_length=50, verbose_name='アイテムタイプ')),
                ('condition', models.CharField(max_length=5, verbose_name='状態ランク')),
                ('text', models.TextField(verbose_name='備考')),
            ],
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Condition',
        ),
        migrations.DeleteModel(
            name='Item_model',
        ),
    ]
