# Generated by Django 2.2.15 on 2020-08-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200827_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('shirt', 'シャツ'), ('pant', 'パンツ'), ('Tshirt', 'Tシャツ')], default=999, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='condition',
            field=models.CharField(choices=[('s', 'S'), ('a', 'A'), ('b', 'B'), ('c', 'C')], default=998, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='item_model',
            field=models.CharField(default=997, max_length=50, verbose_name='モデル名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='text',
            field=models.TextField(default=996, verbose_name='備考'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
