# Generated by Django 2.2.15 on 2020-09-01 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Item', verbose_name='アイテム'),
        ),
    ]
