# Generated by Django 2.2.15 on 2020-10-18 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201018_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='accounts.Item', verbose_name='アイテム'),
        ),
    ]
